version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Choose either one of the orbs below
  # welcome: circleci/welcome-orb@0.4.1
  # aws-cli: circleci/aws-cli@2.0.3
# Define the jobs we want to run for this project
  aws-cli: circleci/aws-cli@2.0.3
jobs:
  configure_infrastructure: 
    docker:
      - image: python:3.7-alpine3.11 
    steps:
      - checkout
      - add_ssh_keys:
            # You can get this ID in the section where you registered the SSH Key
            fingerprints: ["fc:bc:8b:dc:91:0c:ed:14:ee:cf:eb:de:ae:c5:19:1b"] 
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible

      - run:
        name: Run Playbook and Configure server
        command: |
            ansible-playbook -i inventory.txt main-remote.yml


workflows:
  my_workflow:
      jobs:
        # - create_infrastructure
        - configure_infrastructure
        